# Generated by Django 4.2.6 on 2023-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_messages',
            name='bot_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
